Subject.create(name: 'History')
Subject.create(name: 'Math')
Subject.create(name: 'Science')
Subject.create(name: 'Latin')
Subject.create(name: 'Spanish')
Subject.create(name: 'Reading')

Instrument.create(name: 'Piano')
Instrument.create(name: 'Violin')
Instrument.create(name: 'Guitar')
Instrument.create(name: 'Harmonics')
